### ISSUE TITLE
Photos from different cameras

### ISSUE THREAD

**Issue by BenjaminGrosskopf** [alexbruy/photo2shape#12]
Helleo Alex,

I've got the problem that I can import pictures taken with a camera from Canon without any problems but I cannot import pictures taken with a camera from Nikon. I checked all the Coordinates with the Geosetter and they are the same at all the pictures. Can you please help me finding out what's the problem? Attached you can find two pictures. One of them is taken with the Canon and the other is taken with the Nikon.
![ks_1-241_4](https://user-images.githubusercontent.com/34287540/33634069-3402ee40-da13-11e7-95b9-21603b5fc783.JPG)
![img_8580](https://user-images.githubusercontent.com/34287540/33634085-4706eeec-da13-11e7-9f0e-e1c6894382c7.JPG)

Thanks in advance fpr your help.

Benjamin

**Comment by alexbruy** [comment]
Just tested your images and both were processed correctly with plugin.

**Comment by alexbruy** [comment]
@BenjaminGrosskopf I can not reproduce error using attached images. Do you have anything in the QGIS log, maybe there are some specific steps to reproduce this issue?

**Comment by alexbruy** [comment]
Closed as not reproducible with provided dataset.
