### ISSUE TITLE
Handle invalid date format provided by exifread

### ISSUE THREAD

**Issue by SzieberthAdam** [alexbruy/photo2shape#5]
For our Garmin Oregon 550 `exifread` produces `tags['Image DateTime'].values` like `u'2016:10:27 14:40:23'` instead of the ISOish `u'2016-10-27 14:40:23'`.

This makes it harder to copy data to PostGIS. Either this issue should be fixed by `exifread`, `photo2shape` or one has to define a trigger for it.

**Comment by SzieberthAdam** [comment]
Unfortunately even triggers would be hard to make because typechecking in PostgreSQL is done before triggers fire.

https://www.postgresql.org/message-id/98E759A7-C57A-4065-B24F-30F7B094A901@gmail.com

**Comment by SzieberthAdam** [comment]
Here is the fix:

```
    def _extractImageDateTime(self, tags):
        if 'Image DateTime' in tags:
            s = tags['Image DateTime'].values
            splitted = s.split()
            return splitted[0].replace(u':', u'-') + u' ' + splitted[1]
        return None
```

**Comment by alexbruy** [comment]
I don't think this is a bug. Dates returned in this format by exiftool and also this is how date/time should be stored in EXIF tags according to the specification.

**Comment by SzieberthAdam** [comment]
You are right, according to the EXIF specification:

> The format is "YYYY:MM:DD HH:MM:SS" with time shown in 24-hour format, and the date and time separated by one blank character [20.H].

It is weird to me why the non-ISO standard time format, but it is surely not this plugin's issue.
