### ISSUE TITLE
Python exception when copy/paste path

### ISSUE THREAD

**Issue by m-kuhn** [alexbruy/photo2shape#8]
When the path to the shapefile is copy/pasted (i.e. when the open file dialog has not been used), a python exception is raised because `self.encoding` has not been set.

I think either one of the following would be nice UX enhancements

* make the lineedit readonly
* allow specifying the encoding in the dialog
* provide a default encoding
* make this available as a processing algorithm ;)

**Comment by alexbruy** [comment]
Turning this plugin into Processing algorithm is in the top of my TODO. Unfortunately I'm quite busy these days (preparing new release at work) and don't have enough time to work on my personal projects. But I will try to do something and fix issues ASAP.

**Comment by alexbruy** [comment]
Should be fixed now
